import { app, autoUpdater, BrowserWindow, ipcMain } from 'electron';
import {
    updateElectronApp,
    UpdateSourceType,
    type IUpdateInfo,
} from 'update-electron-app';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        height: 800,
        width: 1000,
        show: false,
        backgroundColor: '#0f172a',
        autoHideMenuBar: app.isPackaged,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            devTools: !app.isPackaged,
        },
    });

    if (app.isPackaged) {
        mainWindow.setMenu(null);
    }

    mainWindow.once('ready-to-show', () => {
        mainWindow?.show();
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
    // Skip auto-updates during local development runs.
    if (app.isPackaged) {
        updateElectronApp({
            updateSource: {
                type: UpdateSourceType.ElectronPublicUpdateService,
                repo: 'aidmet/ManageMe',
            },
            notifyUser: true,
            onNotifyUser: (info: IUpdateInfo) => {
                const payload = {
                    releaseName: info.releaseName,
                    releaseNotes: info.releaseNotes,
                };
                mainWindow?.webContents.send('app-update-ready', payload);
            },
        });
        ipcMain.on('app-install-update', () => {
            autoUpdater.quitAndInstall();
        });
    }
    createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
