import { app, autoUpdater, BrowserWindow, ipcMain } from 'electron';
import {
    updateElectronApp,
    UpdateSourceType,
    type IUpdateInfo,
} from 'update-electron-app';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        height: 800,
        width: 1000,
        show: false,
        backgroundColor: '#0f172a',
        autoHideMenuBar: app.isPackaged,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            devTools: !app.isPackaged,
        },
    });

    if (app.isPackaged) {
        mainWindow.setMenu(null);
    }

    mainWindow.once('ready-to-show', () => {
        mainWindow?.show();
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
    // Skip auto-updates during local development runs.
    if (app.isPackaged) {
        updateElectronApp({
            updateSource: {
                type: UpdateSourceType.ElectronPublicUpdateService,
                repo: 'aidmet/ManageMe',
            },
            notifyUser: true,
            onNotifyUser: (info: IUpdateInfo) => {
                const payload = {
                    releaseName: info.releaseName,
                    releaseNotes: info.releaseNotes,
                };
                mainWindow?.webContents.send('app-update-ready', payload);
            },
        });
        ipcMain.on('app-install-update', () => {
            autoUpdater.quitAndInstall();
        });
    }

    ipcMain.handle('app-check-for-updates', async () => {
        if (!app.isPackaged) {
            return { ok: false, kind: 'not_packaged' as const };
        }
        return await new Promise<
            | { ok: true; kind: 'no_update' }
            | { ok: true; kind: 'update_available' }
            | { ok: false; kind: 'error'; message: string }
        >((resolve) => {
            let settled = false;
            const timeoutMs = 120_000;

            const finish = (
                result:
                    | { ok: true; kind: 'no_update' }
                    | { ok: true; kind: 'update_available' }
                    | { ok: false; kind: 'error'; message: string }
            ): void => {
                if (settled) {
                    return;
                }
                settled = true;
                clearTimeout(timeout);
                autoUpdater.removeListener('update-available', onAvailable);
                autoUpdater.removeListener('update-not-available', onNotAvailable);
                autoUpdater.removeListener('error', onError);
                resolve(result);
            };

            const timeout = setTimeout(() => {
                finish({
                    ok: false,
                    kind: 'error',
                    message:
                        'Update check timed out. Check your connection and try again.',
                });
            }, timeoutMs);

            const onAvailable = (): void => {
                finish({ ok: true, kind: 'update_available' });
            };

            const onNotAvailable = (): void => {
                finish({ ok: true, kind: 'no_update' });
            };

            const onError = (err: Error): void => {
                finish({
                    ok: false,
                    kind: 'error',
                    message: err.message || 'Update check failed.',
                });
            };

            autoUpdater.once('update-available', onAvailable);
            autoUpdater.once('update-not-available', onNotAvailable);
            autoUpdater.once('error', onError);

            try {
                autoUpdater.checkForUpdates();
            } catch (err) {
                finish({
                    ok: false,
                    kind: 'error',
                    message:
                        err instanceof Error ? err.message : String(err),
                });
            }
        });
    });

    createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
